title: hyeon.log
description: 키보드가 망가지도록 공부하기
url: "https://kkr010128.github.io"
baseurl: ""
lang: ko-KR
timezone: Asia/Seoul
markdown: kramdown
highlighter: rouge
permalink: /:title/

analytics:
  google:
    measurement_id: "G-S5JKF3RE2G"

comments:
  provider: "giscus"
  disqus:
    shortname: ""
  giscus:
    repo: "kkr010128/kkr010128.github.io"
    repo_id: "R_kgDOToIqkw"
    category: "Announcements"
    category_id: "DIC_kwDOToIqk84DCiaL"
    mapping: "pathname"
    strict: true
    reactions_enabled: true
    emit_metadata: false
    input_position: "top"
    lang: "ko"
    loading: "lazy"
    theme_light: "/assets/css/giscus-velog-light.css"
    theme_dark: "/assets/css/giscus-velog-dark.css"

search:
  provider: local
  algolia:
    app_id: ""
    api_key: ""
    index_name: ""
    insights: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "assets"
    values:
      layout: null
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - Jenkinsfile
  - LICENSE
  - NOTICE.md
  - README.md
  - output
  - scripts
  - vendor
